name: 'Request authorization'
description: 'Request authorization to merge'


inputs:
  app-id:
    description: "GitHub app ID"
    required: true

  private-key:
    description: "GitHub app private key"
    required: true

  closing-pr:
    description: "Set to true when pull requests are getting closed"
    type: boolean
    default: true


runs:
  using: "composite"
  steps:
    - name: Split repository owners and names
      shell: bash
      env:
        REPOSITORY: ${{ github.repository }}
        ACTION_REPOSITORY: ${{ github.action_repository }}
      run: |
        REPOSITORY_OWNER="${REPOSITORY%%/*}"
        REPOSITORY_NAME="${REPOSITORY#*/}"

        ACTION_REPOSITORY_OWNER="${ACTION_REPOSITORY%%/*}"
        ACTION_REPOSITORY_NAME="${ACTION_REPOSITORY#*/}"

        echo "REPOSITORY=$REPOSITORY" | tee -a "$GITHUB_ENV"
        echo "REPOSITORY_OWNER=$REPOSITORY_OWNER" | tee -a "$GITHUB_ENV"
        echo "REPOSITORY_NAME=$REPOSITORY_NAME" | tee -a "$GITHUB_ENV"

        echo "ACTION_REPOSITORY=$ACTION_REPOSITORY" | tee -a "$GITHUB_ENV"
        echo "ACTION_REPOSITORY_OWNER=$ACTION_REPOSITORY_OWNER" | tee -a "$GITHUB_ENV"
        echo "ACTION_REPOSITORY_NAME=$ACTION_REPOSITORY_NAME" | tee -a "$GITHUB_ENV"

    - name: Create application token for current repository
      if: ${{ inputs.closing-pr != 'true' }}
      uses: actions/create-github-app-token@v1
      id: current-app-token
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
        owner: ${{ env.REPOSITORY_OWNER }}
        repositories: ${{ env.REPOSITORY_NAME }}

    - name: Set status as pending
      if: ${{ inputs.closing-pr != 'true' }}
      uses: ouzi-dev/commit-status-updater@v2
      env:
        # Hardcoded for simplicity
        STATUS_NAME: freeze
      with:
        token: ${{ steps.current-app-token.outputs.token }}
        name: ${{ env.STATUS_NAME }}
        status: "pending"
        description: "Requesting authorization"

    - name: Create application token for the action repository
      uses: actions/create-github-app-token@v1
      id: action-app-token
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
        owner: ${{ env.ACTION_REPOSITORY_OWNER }}
        repositories: ${{ env.ACTION_REPOSITORY_NAME }}

    - name: Send repository dispatch to request authorization
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ steps.action-app-token.outputs.token }}
        repository: ${{ env.ACTION_REPOSITORY }}
        event-type: request
        client-payload: |
          {
            "repository": "${{ env.REPOSITORY }}",
            "pull_request": "${{ github.event.pull_request.number }}",
            "git_sha": "${{ github.event.pull_request.head.sha }}",
            "best_effort": "${{ inputs.closing-pr }}"
          }
