name: 'Triggering Artikodin Controller'
description: 'Triggering the Artikodin controller to update pull request status'


inputs:
  contents-app-id:
    description: "GitHub app ID for access to contents repositories"
    required: true

  contents-private-key:
    description: "GitHub app private key for access to contents repositories"
    required: true

  controller-app-id:
    description: "GitHub app ID for access to controller repositories"
    required: true

  controller-private-key:
    description: "GitHub app private key for access to controller repositories"
    required: true

  target-from-head-ref:
    description: "Parse the specified head ref to get the repository and pull request number"

  target-repository:
    description: "The target repository"

  exception-pull-request:
    description: "The number of the exception request pull request for which to request the exception"

  target-pull-request:
    description: "The number of the pull request for which to request the exception (contents repository)"

  target-git-sha:
    description: "The sha of the commit to update the status for"

  target-merge-group-head-ref:
    description: "The head ref of the merge group"

  request-exception:
    description: "Request an exception for merge"
    type: boolean
    default: false

  closing-pr:
    description: "Set to true when pull requests are getting closed"
    type: boolean
    default: true


runs:
  using: "composite"
  steps:
    # To access private repositories, use the following three steps
    # - name: Prepare inputs
      # shell: bash
      # env:
        # ACTION_REPOSITORY: ${{ github.action_repository }}
      # run: |
        # ACTION_REPOSITORY_OWNER=${ACTION_REPOSITORY%/*}
        # ACTION_REPOSITORY_NAME=${ACTION_REPOSITORY##*/}
        # echo "ACTION_REPOSITORY=$ACTION_REPOSITORY" | tee -a "$GITHUB_ENV"
        # echo "ACTION_REPOSITORY_OWNER=$ACTION_REPOSITORY_OWNER" | tee -a "$GITHUB_ENV"
        # echo "ACTION_REPOSITORY_NAME=$ACTION_REPOSITORY_NAME" | tee -a "$GITHUB_ENV"

    # - name: Create GitHub app token to checkout the controller repository
      # uses: actions/create-github-app-token@v1
      # id: contents-app-token
      # with:
        # app-id: ${{ inputs.contents-app-id }}
        # private-key: ${{ inputs.contents-private-key }}
        # owner: ${{ env.ACTION_REPOSITORY_OWNER }}
        # repositories: ${{ env.ACTION_REPOSITORY_NAME }}

    # - name: Checkout controller repository
      # uses: actions/checkout@v4
      # with:
        # repository: ${{ env.ACTION_REPOSITORY }}
        # ref: main
        # token: ${{ steps.contents-app-token.outputs.token }}
        # persist-credentials: false

    # To accesss public repositories, use the following step
    - name: Checkout controller repository
      uses: actions/checkout@v4
      env:
        ACTION_REPOSITORY: ${{ github.action_repository }}
      with:
        repository: ${{ env.ACTION_REPOSITORY }}
        ref: main

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3'
        cache: 'pip'

    - name: Install dependencies
      shell: bash
      run: |
        pip install -r controller/requirements.txt

    - name: Run update script
      shell: bash
      env:
        ARTIKODIN_CONTENTS_APP_ID: ${{ inputs.contents-app-id }}
        ARTIKODIN_CONTENTS_PRIVATE_KEY: ${{ inputs.contents-private-key }}
        ARTIKODIN_CONTROLLER_APP_ID: ${{ inputs.controller-app-id }}
        ARTIKODIN_CONTROLLER_PRIVATE_KEY: ${{ inputs.controller-private-key }}
        BEST_EFFORT: ${{ inputs.request-exception == 'false' && inputs.closing-pr == 'true' && '--best-effort' || '' }}
        EXCEPTION_HEAD_REF: ${{ inputs.target-from-head-ref }}
        EXCEPTION_PULL_REQUEST: ${{ inputs.exception-pull-request }}
        TARGET_GIT_SHA: ${{ inputs.target-git-sha }}
        TARGET_MERGE_GROUP_HEAD_REF: ${{ inputs.target-merge-group-head-ref }}
        VERB: ${{ inputs.request-exception == 'true' && 'request' || 'update' }}
      run: |
        ARGS=()
        if [[ -n "$EXCEPTION_PULL_REQUEST" ]]; then
          ARGS+=("--exception-pull-request" "$EXCEPTION_PULL_REQUEST")
        elif [[ -n "$EXCEPTION_HEAD_REF" ]]; then
          ARGS+=("--exception-head-ref" "$EXCEPTION_HEAD_REF")
        elif [[ -n "$TARGET_MERGE_GROUP_HEAD_REF" ]]; then
          ARGS+=("--merge-group-head-ref" "$TARGET_MERGE_GROUP_HEAD_REF")
          [[ -n "$TARGET_GIT_SHA" ]] && ARGS+=("--commit" "$TARGET_GIT_SHA")
        else
          ARGS+=("--repository" "${{ env.TARGET_REPOSITORY }}")
          ARGS+=("--pull-request" "$TARGET_PULL_REQUEST")
          [[ -n "$TARGET_GIT_SHA" ]] && ARGS+=("--commit" "$TARGET_GIT_SHA")
        fi

        ./controller/run.py \
          --controller-app-id "$ARTIKODIN_CONTROLLER_APP_ID" \
          --controller-private-key "$ARTIKODIN_CONTROLLER_PRIVATE_KEY" \
          --contents-app-id "$ARTIKODIN_CONTENTS_APP_ID" \
          --contents-private-key "$ARTIKODIN_CONTENTS_PRIVATE_KEY" \
          ${{ env.VERB }} ${{ env.BEST_EFFORT }} \
          "${ARGS[@]}"
