name: 'Triggering Artikodin Controller'
description: 'Triggering the Artikodin controller to update pull request status'


inputs:
  contents-app-id:
    description: "GitHub app ID for access to contents repositories"
    required: true

  contents-private-key:
    description: "GitHub app private key for access to contents repositories"
    required: true

  controller-app-id:
    description: "GitHub app ID for access to controller repositories"
    required: true

  controller-private-key:
    description: "GitHub app private key for access to controller repositories"
    required: true

  target-from-head-ref:
    description: "Parse the specified head ref to get the repository and pull request number"

  target-repository:
    description: "The target repository"

  controller-pull-request:
    description: "The number of the exception request pull request for which to request the exception"

  target-pull-request:
    description: "The number of the pull request for which to request the exception (contents repository)"

  target-git-sha:
    description: "The sha of the commit to update the status for"

  request-exception:
    description: "Request an exception for merge"
    type: boolean
    default: false

  closing-pr:
    description: "Set to true when pull requests are getting closed"
    type: boolean
    default: true


runs:
  using: "composite"
  steps:
    - name: Split repository owners and names
      shell: bash
      env:
        ACTION_REPOSITORY: ${{ github.action_repository }}
      run: |
        HEAD_REF="${{ inputs.target-from-head-ref }}"
        if [[ "$HEAD_REF" =~ ([^/]*)/([^/]*)/([0-9]*)$ ]]; then
          TARGET_REPOSITORY_OWNER=${BASH_REMATCH[1]}
          TARGET_REPOSITORY_NAME=${BASH_REMATCH[2]}
          TARGET_REPOSITORY="${TARGET_REPOSITORY_OWNER}/${TARGET_REPOSITORY_NAME}"
          TARGET_PULL_REQUEST=${BASH_REMATCH[3]}
        else
          TARGET_REPOSITORY="${{ inputs.target-repository || github.repository }}"
          TARGET_REPOSITORY_OWNER="${TARGET_REPOSITORY%%/*}"
          TARGET_REPOSITORY_NAME="${TARGET_REPOSITORY#*/}"
          TARGET_PULL_REQUEST="${{ inputs.target-pull-request }}"
        fi

        echo "REPOSITORY=$REPOSITORY" | tee -a "$GITHUB_ENV"
        echo "REPOSITORY_OWNER=$REPOSITORY_OWNER" | tee -a "$GITHUB_ENV"
        echo "REPOSITORY_NAME=$REPOSITORY_NAME" | tee -a "$GITHUB_ENV"

        ACTION_REPOSITORY_OWNER="${ACTION_REPOSITORY%%/*}"
        ACTION_REPOSITORY_NAME="${ACTION_REPOSITORY#*/}"

        echo "ACTION_REPOSITORY=$ACTION_REPOSITORY" | tee -a "$GITHUB_ENV"
        echo "ACTION_REPOSITORY_OWNER=$ACTION_REPOSITORY_OWNER" | tee -a "$GITHUB_ENV"
        echo "ACTION_REPOSITORY_NAME=$ACTION_REPOSITORY_NAME" | tee -a "$GITHUB_ENV"

    - name: Create application token for current repository
      if: ${{ inputs.closing-pr != 'true' }}
      uses: actions/create-github-app-token@v1
      id: current-app-token
      with:
        app-id: ${{ inputs.contents-app-id }}
        private-key: ${{ inputs.contents-private-key }}
        owner: ${{ env.TARGET_REPOSITORY_OWNER }}
        repositories: ${{ env.TARGET_REPOSITORY_NAME }}

    - name: Set status as pending
      if: ${{ inputs.closing-pr != 'true' }}
      uses: ouzi-dev/commit-status-updater@v2
      env:
        # Hardcoded for simplicity
        STATUS_NAME: freeze
      with:
        token: ${{ steps.current-app-token.outputs.token }}
        name: ${{ env.STATUS_NAME }}
        status: "pending"
        description: "Requesting authorization"

    - name: Checkout controller repository
      uses: actions/checkout@v4
      with:
        repository: ${{ env.ACTION_REPOSITORY }}
        ref: main

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3'
        cache: 'pip'

    - name: Install dependencies
      shell: bash
      run: |
        pip install -r controller/requirements.txt

    - name: Run update script
      shell: bash
      env:
        ARTIKODIN_CONTROLLER_APP_ID: ${{ inputs.controller-app-id }}
        ARTIKODIN_CONTROLLER_PRIVATE_KEY: ${{ inputs.controller-private-key }}
        ARTIKODIN_CONTENTS_APP_ID: ${{ inputs.contents-app-id }}
        ARTIKODIN_CONTENTS_PRIVATE_KEY: ${{ inputs.contents-private-key }}
        TARGET_REPOSITORY: ${{ github.event.client_payload.repository || inputs.repository }}
        TARGET_PULL_REQUEST: ${{ inputs.target-pull-request }}
        TARGET_GIT_SHA: ${{ inputs.target-git-sha }}
        CONTROLLER_PULL_REQUEST: ${{ inputs.controller-pull-request }}
        BEST_EFFORT: ${{ inputs.closing-pr == 'true' && '--best-effort' || '' }}
      run: |
        ./controller/run.py \
          --controller-app-id "$ARTIKODIN_CONTROLLER_APP_ID" \
          --controller-private-key "$ARTIKODIN_CONTROLLER_PRIVATE_KEY" \
          --contents-app-id "$ARTIKODIN_CONTENTS_APP_ID" \
          --contents-private-key "$ARTIKODIN_CONTENTS_PRIVATE_KEY" \
          update ${{ env.BEST_EFFORT }} \
          ${TARGET_PULL_REQUEST:+--pull-request $TARGET_PULL_REQUEST} \
          ${TARGET_GIT_SHA:+--commit $TARGET_GIT_SHA} \
          ${CONTROLLER_PULL_REQUEST:+--controller-pull-request $CONTROLLER_PULL_REQUEST} \
          --repository "${{ env.TARGET_REPOSITORY }}"

    # - name: Create application token for the action repository
      # uses: actions/create-github-app-token@v1
      # id: action-app-token
      # with:
        # app-id: ${{ inputs.app-id }}
        # private-key: ${{ inputs.private-key }}
        # owner: ${{ env.ACTION_REPOSITORY_OWNER }}
        # repositories: ${{ env.ACTION_REPOSITORY_NAME }}

    # - name: Send repository dispatch to request authorization
      # uses: peter-evans/repository-dispatch@v2
      # with:
        # token: ${{ steps.action-app-token.outputs.token }}
        # repository: ${{ env.ACTION_REPOSITORY }}
        # event-type: ${{ inputs.request-exception == 'true' && 'request-exception' || 'sync' }}
        # client-payload: |
          # {
            # "repository": "${{ env.TARGET_REPOSITORY }}",
            # "controller_pull_request": "${{ inputs.controller-pull-request }}",
            # "pull_request": "${{ env.TARGET_PULL_REQUEST }}",
            # "git_sha": "${{ inputs.target-git-sha }}",
            # "best_effort": ${{ inputs.closing-pr == 'true' }}
          # }
