up:
  - python: auto
  - custom:
      dir: controller
      meet: pip install -r requirements.txt && pip install -r requirements_calendar.txt

commands:
  check-config:
    name: Checking the configuration of the controller
    run: |
      cd controller
      eval "$(omni hook env 2>/dev/null)"
      ./run.py check-config && echo "Config ok!"
