name: Authorizer
run-name: "Update authorization for ${{ github.event.client_payload.repository || inputs.repository }} (#${{ github.event.client_payload.pull_request || inputs.pull_request }})"


on:
  # Runs on a repository dispatch
  repository_dispatch:
    types:
      - authorizer

  # Runs on a workflow dispatch
  workflow_dispatch:
    inputs:
      repository:
        description: 'The repository for which to authorize the merge'
        required: true
      pull_request:
        description: 'The pull request number to authorize'
        required: true
      git_sha:
        description: 'The git sha to report the status for'
        required: true


concurrency:
  group: ${{ github.workflow }}-${{ github.event.client_payload.repository || inputs.repository }}-${{ github.event.client_payload.pull_request || inputs.pull_request }}
  cancel-in-progress: false


jobs:
  run_update:
    name: Check input

    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r controller/requirements.txt

      - name: Run update script
        env:
          REPOSITORY: ${{ github.repository }}
          TARGET_REPOSITORY: ${{ github.event.client_payload.repository || inputs.repository }}
          TARGET_PULL_REQUEST: ${{ github.event.client_payload.pull_request || inputs.pull_request }}
          TARGET_GIT_SHA: ${{ github.event.client_payload.git_sha || inputs.git_sha }}
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          ./controller/run.py \
            --app-id "$APP_ID" \
            --private-key "$PRIVATE_KEY" \
            --controller-repository "$REPOSITORY" \
            update \
            --repository "$TARGET_REPOSITORY" \
            --pull-request "$TARGET_PULL_REQUEST" \
            --commit "$TARGET_GIT_SHA"

