name: Request sync handler
run-name: "Update authorization for ${{ github.event.client_payload.repository || inputs.repository }} (#${{ github.event.client_payload.pull_request || inputs.pull_request }})"


on:
  # Runs on a repository dispatch
  repository_dispatch:
    types:
      - sync

  # Runs on a workflow dispatch
  workflow_dispatch:
    inputs:
      repository:
        description: 'The repository for which to authorize the merge'
        required: true
      pull_request:
        description: 'The pull request number to authorize'
        required: true
      git_sha:
        description: 'The git sha to report the status for'
        required: true
      best_effort:
        description: 'Whether to call the controller update in best effort mode'
        type: boolean
        required: true


concurrency:
  group: ${{ github.workflow }}-request-${{ github.event.client_payload.repository || inputs.repository }}-${{ github.event.client_payload.pull_request || inputs.pull_request }}
  cancel-in-progress: false


jobs:
  run_update:
    name: Run controller in update mode

    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r controller/requirements.txt

      - name: Run update script
        env:
          TARGET_REPOSITORY: ${{ github.event.client_payload.repository || inputs.repository }}
          TARGET_PULL_REQUEST: ${{ github.event.client_payload.pull_request || inputs.pull_request }}
          TARGET_GIT_SHA: ${{ github.event.client_payload.git_sha || inputs.git_sha }}
          BEST_EFFORT: ${{ (github.event.client_payload.best_effort || inputs.best_effort) && '--best-effort' || '' }}
          ARTIKODIN_CONTROLLER_APP_ID: ${{ secrets.ARTIKODIN_CONTROLLER_APP_ID }}
          ARTIKODIN_CONTROLLER_PRIVATE_KEY: ${{ secrets.ARTIKODIN_CONTROLLER_PRIVATE_KEY }}
          ARTIKODIN_CONTENTS_APP_ID: ${{ secrets.ARTIKODIN_CONTENTS_APP_ID }}
          ARTIKODIN_CONTENTS_PRIVATE_KEY: ${{ secrets.ARTIKODIN_CONTENTS_PRIVATE_KEY }}
        run: |
          ./controller/run.py \
            --controller-app-id "$ARTIKODIN_CONTROLLER_APP_ID" \
            --controller-private-key "$ARTIKODIN_CONTROLLER_PRIVATE_KEY" \
            --contents-app-id "$ARTIKODIN_CONTENTS_APP_ID" \
            --contents-private-key "$ARTIKODIN_CONTENTS_PRIVATE_KEY" \
            update ${{ env.BEST_EFFORT }} \
            --repository "${{ env.TARGET_REPOSITORY }}" \
            --pull-request "${{ env.TARGET_PULL_REQUEST }}" \
            --commit "${{ env.TARGET_GIT_SHA }}"

