name: Comment handler


on:
  issue_comment:
    types:
      - created


jobs:
  handle_comment:
    name: Handle pull request comment

    runs-on: ubuntu-latest

    # This is hardcoded to avoid spending process time going through
    # the controller run if it is not necessary
    if: |
      github.event.issue.pull_request &&
      github.event.issue.state == 'open' &&
      contains(github.event.issue.labels.*.name, 'exceptions') &&
      contains(github.event.issue.labels.*.name, 'pending') &&
      (github.event.comment.body == '/exception' ||
       startsWith(github.event.comment.body, '/exception ') ||
       startsWith(toJson(github.event.comment.body), '"/exception\n') ||
       startsWith(toJson(github.event.comment.body), '"/exception\r\n'))

    env:
      PR_NUM: ${{ github.event.issue.number }}

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r controller/requirements.txt

      - name: Run update script
        env:
          REPOSITORY: ${{ github.repository }}
          TARGET_REPOSITORY: ${{ github.event.client_payload.repository || inputs.repository }}
          TARGET_PULL_REQUEST: ${{ github.event.client_payload.pull_request || inputs.pull_request }}
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          ./controller/run.py \
            --app-id "$APP_ID" \
            --private-key "$PRIVATE_KEY" \
            --controller-repository "${{ env.REPOSITORY }}" \
            request \
            --repository "${{ env.TARGET_REPOSITORY }}" \
            --pull-request "${{ env.TARGET_PULL_REQUEST }}" \

