name: Review handler


on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

  pull_request_review_comment:


jobs:
  handle-review:
    name: Handle pull request reviews

    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
