name: Resync


on:
  # Run on a schedule, here every 4 hours at past 13
  schedule:
    - cron: "13 */4 * * *"

  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-resync
  cancel-in-progress: false


jobs:
  run_cron:
    name: Run controller in cron mode

    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r controller/requirements.txt

      - name: Run cron script
        env:
          ARTIKODIN_CONTROLLER_APP_ID: ${{ secrets.ARTIKODIN_CONTROLLER_APP_ID }}
          ARTIKODIN_CONTROLLER_PRIVATE_KEY: ${{ secrets.ARTIKODIN_CONTROLLER_PRIVATE_KEY }}
          ARTIKODIN_CONTENTS_APP_ID: ${{ secrets.ARTIKODIN_CONTENTS_APP_ID }}
          ARTIKODIN_CONTENTS_PRIVATE_KEY: ${{ secrets.ARTIKODIN_CONTENTS_PRIVATE_KEY }}
        run: |
          ./controller/run.py \
            --controller-app-id "$ARTIKODIN_CONTROLLER_APP_ID" \
            --controller-private-key "$ARTIKODIN_CONTROLLER_PRIVATE_KEY" \
            --contents-app-id "$ARTIKODIN_CONTENTS_APP_ID" \
            --contents-private-key "$ARTIKODIN_CONTENTS_PRIVATE_KEY" \
            cron

